/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	operatorv1 "knstart/pkg/apis/operator/v1"
	versioned "knstart/pkg/client/clientset/versioned"
	internalinterfaces "knstart/pkg/client/informers/externalversions/internalinterfaces"
	v1 "knstart/pkg/client/listers/operator/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KNLearningInformer provides access to a shared informer and lister for
// KNLearnings.
type KNLearningInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KNLearningLister
}

type kNLearningInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKNLearningInformer constructs a new informer for KNLearning type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKNLearningInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKNLearningInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKNLearningInformer constructs a new informer for KNLearning type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKNLearningInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Xq2005V1().KNLearnings(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Xq2005V1().KNLearnings(namespace).Watch(options)
			},
		},
		&operatorv1.KNLearning{},
		resyncPeriod,
		indexers,
	)
}

func (f *kNLearningInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKNLearningInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kNLearningInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&operatorv1.KNLearning{}, f.defaultInformer)
}

func (f *kNLearningInformer) Lister() v1.KNLearningLister {
	return v1.NewKNLearningLister(f.Informer().GetIndexer())
}
