/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	operatorv1 "knstart/pkg/apis/operator/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKNLearnings implements KNLearningInterface
type FakeKNLearnings struct {
	Fake *FakeXq2005V1
	ns   string
}

var knlearningsResource = schema.GroupVersionResource{Group: "xq2005.com", Version: "v1", Resource: "knlearnings"}

var knlearningsKind = schema.GroupVersionKind{Group: "xq2005.com", Version: "v1", Kind: "KNLearning"}

// Get takes name of the kNLearning, and returns the corresponding kNLearning object, and an error if there is any.
func (c *FakeKNLearnings) Get(name string, options v1.GetOptions) (result *operatorv1.KNLearning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(knlearningsResource, c.ns, name), &operatorv1.KNLearning{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorv1.KNLearning), err
}

// List takes label and field selectors, and returns the list of KNLearnings that match those selectors.
func (c *FakeKNLearnings) List(opts v1.ListOptions) (result *operatorv1.KNLearningList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(knlearningsResource, knlearningsKind, c.ns, opts), &operatorv1.KNLearningList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &operatorv1.KNLearningList{ListMeta: obj.(*operatorv1.KNLearningList).ListMeta}
	for _, item := range obj.(*operatorv1.KNLearningList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kNLearnings.
func (c *FakeKNLearnings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(knlearningsResource, c.ns, opts))

}

// Create takes the representation of a kNLearning and creates it.  Returns the server's representation of the kNLearning, and an error, if there is any.
func (c *FakeKNLearnings) Create(kNLearning *operatorv1.KNLearning) (result *operatorv1.KNLearning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(knlearningsResource, c.ns, kNLearning), &operatorv1.KNLearning{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorv1.KNLearning), err
}

// Update takes the representation of a kNLearning and updates it. Returns the server's representation of the kNLearning, and an error, if there is any.
func (c *FakeKNLearnings) Update(kNLearning *operatorv1.KNLearning) (result *operatorv1.KNLearning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(knlearningsResource, c.ns, kNLearning), &operatorv1.KNLearning{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorv1.KNLearning), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKNLearnings) UpdateStatus(kNLearning *operatorv1.KNLearning) (*operatorv1.KNLearning, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(knlearningsResource, "status", c.ns, kNLearning), &operatorv1.KNLearning{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorv1.KNLearning), err
}

// Delete takes name of the kNLearning and deletes it. Returns an error if one occurs.
func (c *FakeKNLearnings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(knlearningsResource, c.ns, name), &operatorv1.KNLearning{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKNLearnings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(knlearningsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &operatorv1.KNLearningList{})
	return err
}

// Patch applies the patch and returns the patched kNLearning.
func (c *FakeKNLearnings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *operatorv1.KNLearning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(knlearningsResource, c.ns, name, pt, data, subresources...), &operatorv1.KNLearning{})

	if obj == nil {
		return nil, err
	}
	return obj.(*operatorv1.KNLearning), err
}
